# use the minimal jekyll theme for the site
theme: jekyll-theme-minimal
title: Joy of Software
description: Minimal is a theme for GitHub Pages.
logo: /assets/img/logo.png
show_downloads: false
timezone: America/New_York
google_analytics:
theme: jekyll-theme-minimal
