# use the minimal jekyll theme for the site
theme: jekyll-theme-minimal
title: Joy of Software
description: musing at the confluence of data, software, and security
logo: /assets/img/logo.png
show_downloads: false
timezone: America/New_York
theme: jekyll-theme-minimal
