# use the minimal jekyll theme for the site
title: Joy of Software
description: musing at the confluence of data, software and security
logo: /assets/img/logo-540x360.png
show_downloads: false
timezone: America/New_York
